/**
 * Crafted by Aidar Ibatullin <amazing.space.invader@gmail.com>
 * 14.03.17
 */

export const API_CUSTOMERS = '/api/v1/customers';
export const API_PRODUCTS = '/api/v1/products';
export const API_INVOICES = '/api/v1/invoices';

export const FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE';

export const ADD_CUSTOMER_REQUEST = 'ADD_CUSTOMER_REQUEST';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_FAILURE = 'ADD_CUSTOMER_FAILURE';

export const DELETE_CUSTOMER_REQUEST = 'DELETE_CUSTOMER_REQUEST';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAILURE = 'DELETE_CUSTOMER_FAILURE';

export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE';

export const OPEN_MODAL_ADD_CUSTOMER = 'OPEN_MODAL_ADD_CUSTOMER';
export const CLOSE_MODAL_ADD_CUSTOMER = 'CLOSE_MODAL_ADD_CUSTOMER';

export const OPEN_MODAL_DELETE_CUSTOMER = 'OPEN_MODAL_DELETE_CUSTOMER';
export const CLOSE_MODAL_DELETE_CUSTOMER = 'CLOSE_MODAL_DELETE_CUSTOMER';

export const OPEN_MODAL_EDIT_CUSTOMER = 'OPEN_MODAL_EDIT_CUSTOMER';
export const CLOSE_MODAL_EDIT_CUSTOMER = 'CLOSE_MODAL_EDIT_CUSTOMER';